### ISSUE TITLE
IT'S THAT TIME AGAIN! 🎉

### ISSUE THREAD

**Issue by Mike-E-wins** [zvirja/ReSharperHelpers#11]
We need a 2020.1 build when you can please. 😁

Out of 17 extensions that I just installed, only two were not available: this one, and [Exceptional](https://github.com/CSharpAnalyzers/ExceptionalReSharper/issues/114).

---

A kind reminder to please vote to improve the extension model experience so we don't have to continually nag extension authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by zvirja** [comment]
@Mike-E-wins Just saw it. I think it's done by now 😊

**Comment by Mike-E-wins** [comment]
Thank you for all your diligent work out there, @zvirja ... and for putting up with our nags. 😊
