### ISSUE TITLE
Please release a R# 2020.2 version

### ISSUE THREAD

**Issue by szilardmoncz** [zvirja/ReSharperHelpers#12]

**Comment by zvirja** [comment]
Will do later today. Sorry for the inconvenience, am on vacation 😊

**Comment by zvirja** [comment]
Appeared to be not that smooth and requires me to do a bit of testing. Will release on Tuesday!

Sorry for the inconvenience

**Comment by zvirja** [comment]
Done. The plugin will appear soon in the gallery after approval by JB team!

**Comment by szilardmoncz** [comment]
Thanks for the quick reaction and the continuous status messages.
