### ISSUE TITLE
"Cleanup git modified code" crashes with VS 2022 and R# 2021.2 EXP 01 (preview)

### ISSUE THREAD

**Issue by matlemuzic** [zvirja/ReSharperHelpers#15]
When I try to "Cleanup git modified code" with VS 2022 and R# 2021.2 EXP 01 (preview) I get a nasty crash, something about libgit2sharp.

See image below:

![afbeelding](https://user-images.githubusercontent.com/86775946/130796371-7cac9e14-e1c0-4350-b56d-70267d5cf237.png)

It works with VS 2019 with the same R# plugin version.

**Comment by zvirja** [comment]
@matlemuzic Thank you for the report! That is because I do not exclude a 64 bit version of the native image 😢 
I'll build and publish a fix soon!

**Comment by zvirja** [comment]
I've just pushed the fix - v5.10.1. It's being moderated at the moment and should appear soon 😊 Thank you very much for report again!
