### ISSUE TITLE
2021.3 EAP Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [zvirja/ReSharperHelpers#16]
It would be super useful/valuable to have this extension supported for 2021.3 EAP.  A bunch of extensions are there already:
https://www.jetbrains.com/resharper/nextversion/#section=windows

Thank you for any consideration!

**Comment by zvirja** [comment]
Good day! Thanks for raising. I'm happy I am one step ahead this time, as I also use VS 2022 Preview 😅 

You can consume preview version of plugin from here: https://github.com/zvirja/ReSharperHelpers#pre-release-builds. It should work. Let me know if you see issues!

Notice, I've also changed "Copy FQN" quick action and moved it. In case you used it, read more [here](https://github.com/zvirja/ReSharperHelpers/tree/develop#copy-full-class-name).

Have a great weekend!
