### ISSUE TITLE
No Longer Can Create Test Files :(

### ISSUE THREAD

**Issue by Mike-E-angelo** [zvirja/ReSharperHelpers#17]
Hey there,

Unfortunately it no longer appears that I can create test files for my projects.  Please see this SLN:
https://github.com/DragonSpark/Framework/blob/master/The%20DragonSpark%20Framework.sln

Note this configuration:
https://github.com/DragonSpark/Framework/blob/master/DragonSpark.Presentation/Properties/AssemblyInfo.cs

Attempt to hit `Alt-Enter` at this line:
https://github.com/DragonSpark/Framework/blob/master/DragonSpark.Presentation/Environment/Browser/IsBot.cs#L8

This is what I see:
![](https://i.imgur.com/MO0ne3i.png)

I also tried using `.editorconfig` but that doesn't seem to do anything:
https://github.com/DragonSpark/Framework/blob/master/DragonSpark.Presentation/.editorconfig

Any assistance would be greatly appreciated!

**Comment by zvirja** [comment]
Oh, sorry, early morning and I'm not reading text entirely 😖 Let me check your solution and get back in a moment

**Comment by zvirja** [comment]
gosh, it took me 2 hours to understand the root cause.

That's because the `.editorconfig` file is wrong - you have to specify the scope of applicability. Also no need for quotes:

```
[*.cs]
resharperhelpers_tests_project_name = DragonSpark.Presentation.Testing
```

This one works like a charm 😊

**Comment by Mike-E-angelo** [comment]
Thank you so much @zvirja! That _does_ work like a charm. 😁  I certainly appreciate all the assistance you have provided over the years.  Strange to think it's been that long!  Thank you nonetheless. 🙏

**Comment by Mike-E-angelo** [comment]
@zvirja just a quick note that after many many months of friction and obstacles, I have finally been able to get tests made for my components as desired and it is SO AMAZING!!!  The `.editorconfig` works like a champ and I have been copying/pasting/replacing as needed.

_Thank you so very much_ for putting this together and sticking with it, as well as putting up with all my issues.  It's definitely such a relief to be able to slam `ALT-Enter` and get some tests made. 

👍👍👍🙏🙏🙏

**Comment by Mike-E-angelo** [comment]
A little shout out here: https://twitter.com/Mike_E_angelo/status/1524798669509300227
