### ISSUE TITLE
2022.1 EAP Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [zvirja/ReSharperHelpers#18]
Unfortunately Visual Studio 17.2 Preview 2.1 totally destroyed R#, and a new EAP is the only way to use it in this version:

https://youtrack.jetbrains.com/issue/RSRP-488220

Any efforts towards a 2022.1 EAP for this extension would be appreciated. 🙏

**Comment by zvirja** [comment]
Good day! I saw that they recently published `2021.3.3` which was meant to fix that bug. So I guess this could wait till they publish release (so I can push a release version of this as usual)?

**Comment by Mike-E-angelo** [comment]
Actually @zvirja it's `2021.3.4` which I have reverted to and am using it now, along with your extension again. 😁  I have no need for this anymore but you can keep it open if you feel it's necessary. :)

**Comment by Mike-E-angelo** [comment]
Actually @zvirja it's `2021.3.4` which I have reverted to and am using it now, along with your extension again. 😁  I have no need for this anymore but you can keep it open if you feel it's necessary. :)
