### ISSUE TITLE
2022.2 Version is Launched

### ISSUE THREAD

**Issue by Mike-E-angelo** [Zvirja/ReSharperHelpers#20]
Any chance to get a new version for 2022.2, released yesterday? 👍🙏

**Comment by zvirja** [comment]
Thanks for reminding 😊 Will do later today!

**Comment by zvirja** [comment]
Published. Should appear soon once moderation will be done.

BTW still decided to not opt-in into floating version, so I can quickly re-test it for each version of R#. For most of the updates I actually had to tweak the code to fix the complication, so do not see huge win from that anyway 😉 

So thanks for doing a good service and keep reminding me of updates 😊

**Comment by Mike-E-angelo** [comment]
Happy to help!
🙏🙏🙏
