### ISSUE TITLE
R# 2022.3 Support Please :D

### ISSUE THREAD

**Issue by Mike-E-angelo** [zvirja/ReSharperHelpers#23]
Thank you and Happy Holidays 🎄⛄🎅

**Comment by zvirja** [comment]
Enjoy! Have just published it. Got a delay as I was working on adding Rider support as well, so broke things right before the release 🤣 But will add Rider version a bit later after all.

Have great holidays as well 😊

**Comment by theit8514** [comment]
@zvirja The artifact of 7.3 does not have the libgit2 native libraries included. I get a DLL not found exception when trying to perform the git modified cleanup process.

Performing a manual pack on the project creates a nupkg with the libraries.

**Comment by zvirja** [comment]
Wow, let me please investigate that!

**Comment by zvirja** [comment]
@theit8514 I've just pushed updated version of plugin. Thank you for pointing to the issue, it was quite tricky actually 😉 

The version 7.3.1 should appear soon after the plugin verification.
