### ISSUE TITLE
"Cleanup git modified code..." errors out due to long paths not supported

### ISSUE THREAD

**Issue by WiiPlayer2** [zvirja/ReSharperHelpers#24]
In one of our projects we have files with very long names (cannot be changed) and when I'm trying to cleanup all modified files it errors out with a message box containing a stacktrace of an libgit2sharp exception describing that the path is too long.

According to an open issue in libgit2sharp this problem has been fixed by updating the native dependency but as it seems ReSharperHelpers uses an older version. (Issue: https://github.com/libgit2/libgit2sharp/issues/1805)

![image](https://user-images.githubusercontent.com/4729866/220855172-49761b03-834c-4eec-90c9-a774e4decc71.png)

**Comment by zvirja** [comment]
Good day! Sorry for the late reply! I'm updating the version in the newly released version. Should be published soon later today

**Comment by zvirja** [comment]
Actually let me re-test it, not sure it got fixed..
