### ISSUE TITLE
Support custom assertion in context actions

### ISSUE THREAD

**Issue by imanushin** [zvirja/ReSharperHelpers#4]
It is better to have customization for action "Assert Is Not Null".

![image](https://cloud.githubusercontent.com/assets/4425474/20625816/a0731894-b326-11e6-8417-9148d0ad5535.png)

There are different assertion function, for example:
Guard.IsNotNull(myArg, "myArg");

Of from this - https://www.nuget.org/packages/CheckContracts/ :
Validate.ArgumentIsNotNull(myArg, nameof(myArg));

**Comment by Zvirja** [comment]
For now no, class and method names [are hardcoded](https://github.com/Zvirja/ReSharperHelpers/blob/master/AlexPovar.ReSharperHelpers/ContextActions/AssertParameterNotNullAction.cs#L25-L27).

I'll think of improving that in further versions, never thought it might be necessary. Likely, I'll just ask to specify the full class name.

If you wish, you could fire a PR :)

**Comment by zvirja** [comment]
I'll move this to Won't fix. The reason is that R# [introduced](https://www.jetbrains.com/resharper/eap/) (in eap 6) custom assertions functionality, so this feature will be removed from the extension in the nearby future.
