### ISSUE TITLE
Support For CreateExtension action

### ISSUE THREAD

**Issue by osoykan** [zvirja/ReSharperHelpers#5]
Hi @Zvirja,

If any support could be for **CreateExtension** action it would be great. 

Example scenario:

![image](https://cloud.githubusercontent.com/assets/9823085/21289332/6f3896d0-c4a3-11e6-9d48-23ed8b912bfd.png)

When we hit Alt + Enter, ReSharperHelpers could suggest us to create an extension for `ApplyLifeStyleFor` method which creates new ".cs" file for this extension based on type that pointed with _dot_ (e.g) in here Castle's `ComponentRegistration<T>`. So our class name would be "ComponentRegistrationExtensions.cs"

So our extension is:

**ComponentRegistrationExtension.cs :**

```csharp
public static class ComponentRegistrationExtensions
{
    public static ComponentRegistration<T> ApplyLifeStyleFor<T>(this ComponentRegistration<T> registration, DependencyLifeStyle lifeStyle) where T : class
    {
        switch (lifeStyle)
        {
            case DependencyLifeStyle.Singleton:
                return registration.LifestyleSingleton();
            case DependencyLifeStyle.Transient:
                return registration.LifestyleTransient();
            default:
                return registration;
        }
    }
}

```
what do you think:)

Thanks.

**Comment by Zvirja** [comment]
Sorry for a bit belated reply. I've tried to think about your idea and specification for its implementation.  
Basically, I see too many uncertainty here. Consider the following:

1. If "current object" implements a set of interfaces or derives from other classes, which exact type should be used for the `this` argument?
2. Where should the newly created class be located? I don't like an idea to create a file near the current file. That behavior is not very flexible and might not cover all the needs. Instead, I more like idea to put it near the current class within the same file. But if that appears that class is nested or partial, it isn't clear where exactly we should create the extension container class. 
3. Finally, what should be the name of this container class? If we don't know which type to use as a base, we cannot guess the container name. Also, what should we do if class with the same name already exists?

Even if that it's quite easy to implement wish from the technical perspective, I cannot find a shape for this to make it convenient for each potential user :(

**Comment by osoykan** [comment]
I see your concerns and you are right. But let's expand the way we thought;

> If "current object" implements a set of interfaces or derives from other classes, which exact type should be used for the this argument?

We can provide implemented interfaces and base types to user to select one of them if possible ?.

> Where should the newly created class be located?

This is a problem yes. But generally extensions are located in a different folder same csproj or Common/Core csproj. I think user can change its directory afterward. If we consider your partial case, then you are right we can't locate to destination. IMHO, different ".cs" file seems a proper way.

> Finally, what should be the name of this container class

This should be based on user's selection which i stated first clause.

**Comment by zvirja** [comment]
Thinking even more about this I still feel a lot of uncertainty here. R# breaks their API each release, so it will costs to support it in each new release. The need in extension creation is very rare for me, so I'll label this feature as `Won't fix`  and will close it.

If you need it, you can send a PR and re-open this issue. If we find it doesn't require too much code - we could potentially include it in the plugin.. Also you can always create your own plugin - it isn't too hard 😉
