### ISSUE TITLE
Rename Test Files When Source Files are Renamed

### ISSUE THREAD

**Issue by Mike-E-angelo** [zvirja/ReSharperHelpers#7]
First off, super incredible extension!  Thank you so much for taking the time to put these really nice features together.  

I am a fan of your test class generation especially.  One thing I have noticed, however, is that if the source class changes, the corresponding test class doesn't.  Is it perhaps possible to also change the test class name as well?

**Comment by zvirja** [comment]
Thanks for raising this wish. Yep, that would be an awesome feature. Some time ago I also looked into that, but found that feature is not very trivial.

I'll take a look again and will try to do that. If will be unable - will report that here.

**Comment by Mike-EEE** [comment]
Great!  Thanks for any consideration/efforts.

**Comment by Mike-EEE** [comment]
FWIW, we can close this issue as this seems to be addressed now.  I'm not sure if it's another extension I have, or if it's baked into R# now, but when I rename an entity it finds test files that are related to it and renames them for me.  So, problem solved. 😆

**Comment by zvirja** [comment]
Just tested by renaming the class - test class name (and test file name) were not updated.
Could you ensure that you don't have other extensions? 😉

**Comment by Mike-EEE** [comment]
LOL omg and the day was starting off so well, hahaha... Yes, indeed, I do have another extension that might be causing this and that is [TestLinker](https://github.com/matkoch/TestLinker).

This is really embarrassing to admit, but I think I got the two projects confused. 😞 Many many apologies!!

**Comment by Mike-E-angelo** [comment]
Looks like there's an extension for this now. 👍
