### ISSUE TITLE
Alt-Enter on Method Name -> Create New Test

### ISSUE THREAD

**Issue by Mike-EEE** [zvirja/ReSharperHelpers#8]
This would be invaluable for code coverage, or really in general from a testing perspective.  I am basically creating tests around older/imported code, and I am building tests around them.  Of course they show up in VS/R# as unused, so they stick out like a sore thumb, but when I hit Alt-Enter, nothing is shown to provide/create a test around it.  It would be super cool to have the ability to do this.

**Comment by zvirja** [comment]
I'm quite not sure what exactly you would like to have. If you have unused method, than it's better to remove it from code 😉 Could you provide a small demo with feature description and the desired behavior?

Thanks.

**Comment by Mike-EEE** [comment]
Hah!  That is a good point. It is unused until there is a test written around it, in this case. :)  Or it may be a method that was used at one point and is no longer used, but could be valuable in the future.  In any case, the method doesn't have to be unused.  

Quite simply, the expected behavior is exactly what you get when you have the cursor in the test name, except instead of "Create Test File", it's "Create Test Method".  When selected, the test file is loaded (or created if not already), and a method is created in that test file that is the same name as the method in the subject class.

This is the basic workflow I go through now:
https://www.screencast.com/t/lteN5DtBA3

Even better if it adds AutoFixture attributes:
https://www.screencast.com/t/FNrpUnXrC2

👼 

No worries if the value doesn't translate here.  I thought I would bring it up to see if it was worth exploring. :)

**Comment by zvirja** [comment]
Thanks for sharing those samples and 👍 for the AutoFixture usage 😉

You described that in a way I approximately expected. Well, I have concerns regarding this feature:
- you expect that a test for a particular type's method would be prefixed by the method name. In fact that convention is followed relatively rarely from my experience and personally I use it not so often.
- the Alt-Enter actions list will be polluted by an additional item which might be not frequently used, however you will see it for each time.
- personally I don't need/like that feature, but it will cost a lot to support it (as JetBrains changes their API in each update). 

Given that I'd prefer to not include and support this feature as it's very specific and has limited applicability.

----

As for the demos you showed, I'd suggest to create a better R# templates, so it will go simpler 😄 For instance, I have a `theoryAutoNData` template which inserts the following snippet (with my custom AutoData attribute):
```c#
[Theory, AutoNData]
public void $TESTNAME$($parameters$)
{
  // arrange
  // act

  // assert
}
```

So it's quicker to create a test and typing of the method's name (when required) is not so boring 😅

**Comment by Mike-EEE** [comment]
Alright cool.  Sorry for the delay here, I was browsing for some more documentation and realized that I had this open still.  Thanks again for your consideration/discussion.
